/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace VaultLeaderboard {
  export type EntryStruct = {
    player: AddressLike;
    tier: BigNumberish;
    completionTime: BigNumberish;
    score: BigNumberish;
  };

  export type EntryStructOutput = [
    player: string,
    tier: bigint,
    completionTime: bigint,
    score: bigint
  ] & { player: string; tier: bigint; completionTime: bigint; score: bigint };
}

export interface VaultLeaderboardInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_ENTRIES"
      | "bestScore"
      | "getEntries"
      | "isRecorder"
      | "leaderboard"
      | "owner"
      | "recordScore"
      | "renounceOwnership"
      | "setRecorder"
      | "totalEntries"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "RecorderUpdated"
      | "ScoreRecorded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_ENTRIES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bestScore",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntries",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isRecorder",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "leaderboard",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordScore",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setRecorder",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "totalEntries",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_ENTRIES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bestScore", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getEntries", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isRecorder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "leaderboard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRecorder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalEntries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecorderUpdatedEvent {
  export type InputTuple = [recorder: AddressLike, status: boolean];
  export type OutputTuple = [recorder: string, status: boolean];
  export interface OutputObject {
    recorder: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreRecordedEvent {
  export type InputTuple = [
    player: AddressLike,
    tier: BigNumberish,
    score: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    tier: bigint,
    score: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    player: string;
    tier: bigint;
    score: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VaultLeaderboard extends BaseContract {
  connect(runner?: ContractRunner | null): VaultLeaderboard;
  waitForDeployment(): Promise<this>;

  interface: VaultLeaderboardInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_ENTRIES: TypedContractMethod<[], [bigint], "view">;

  bestScore: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEntries: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [VaultLeaderboard.EntryStructOutput[]],
    "view"
  >;

  isRecorder: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  leaderboard: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        player: string;
        tier: bigint;
        completionTime: bigint;
        score: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  recordScore: TypedContractMethod<
    [player: AddressLike, tier: BigNumberish, completionTime: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setRecorder: TypedContractMethod<
    [recorder: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  totalEntries: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_ENTRIES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "bestScore"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEntries"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [VaultLeaderboard.EntryStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRecorder"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "leaderboard"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        player: string;
        tier: bigint;
        completionTime: bigint;
        score: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordScore"
  ): TypedContractMethod<
    [player: AddressLike, tier: BigNumberish, completionTime: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRecorder"
  ): TypedContractMethod<
    [recorder: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalEntries"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RecorderUpdated"
  ): TypedContractEvent<
    RecorderUpdatedEvent.InputTuple,
    RecorderUpdatedEvent.OutputTuple,
    RecorderUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ScoreRecorded"
  ): TypedContractEvent<
    ScoreRecordedEvent.InputTuple,
    ScoreRecordedEvent.OutputTuple,
    ScoreRecordedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RecorderUpdated(address,bool)": TypedContractEvent<
      RecorderUpdatedEvent.InputTuple,
      RecorderUpdatedEvent.OutputTuple,
      RecorderUpdatedEvent.OutputObject
    >;
    RecorderUpdated: TypedContractEvent<
      RecorderUpdatedEvent.InputTuple,
      RecorderUpdatedEvent.OutputTuple,
      RecorderUpdatedEvent.OutputObject
    >;

    "ScoreRecorded(address,uint8,uint32,uint32)": TypedContractEvent<
      ScoreRecordedEvent.InputTuple,
      ScoreRecordedEvent.OutputTuple,
      ScoreRecordedEvent.OutputObject
    >;
    ScoreRecorded: TypedContractEvent<
      ScoreRecordedEvent.InputTuple,
      ScoreRecordedEvent.OutputTuple,
      ScoreRecordedEvent.OutputObject
    >;
  };
}
